wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.5.2
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      - 3
      - 8
      4: 3.5.2
      5: 0.11.2
      8:
      - 1
      - 5
